### Create
### Read
### Update
### Delete

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


numpy is used to create arrays n dimensional and provides multiple operations for tensorflow and machine learning

In [2]:
import numpy as np

1. Create

In [3]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [4]:
data

array([[[0.90624105, 0.47351183, 0.31032366, 0.98039289],
        [0.4580188 , 0.16372524, 0.522577  , 0.70518642],
        [0.32754024, 0.67916447, 0.07233747, 0.22291496]],

       [[0.39631903, 0.0172772 , 0.19376366, 0.28830007],
        [0.07450625, 0.4269751 , 0.39298475, 0.89628301],
        [0.37070787, 0.54500261, 0.57255832, 0.03774601]]])

In [5]:
zeroes 

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
full 

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [7]:
ones 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [9]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
type(arr)

numpy.ndarray

2. Read

In [11]:
# attributes
shape = data.shape
size = data.size
types = data.dtype

In [12]:
shape

(2, 3, 4)

In [13]:
size

24

In [14]:
types

dtype('float64')

In [17]:
# slicing
slicer = data[0:2]

In [16]:
arr

array([[[0.90624105, 0.47351183, 0.31032366, 0.98039289],
        [0.4580188 , 0.16372524, 0.522577  , 0.70518642],
        [0.32754024, 0.67916447, 0.07233747, 0.22291496]],

       [[0.39631903, 0.0172772 , 0.19376366, 0.28830007],
        [0.07450625, 0.4269751 , 0.39298475, 0.89628301],
        [0.37070787, 0.54500261, 0.57255832, 0.03774601]]])

In [18]:
slicer

array([[[0.90624105, 0.47351183, 0.31032366, 0.98039289],
        [0.4580188 , 0.16372524, 0.522577  , 0.70518642],
        [0.32754024, 0.67916447, 0.07233747, 0.22291496]],

       [[0.39631903, 0.0172772 , 0.19376366, 0.28830007],
        [0.07450625, 0.4269751 , 0.39298475, 0.89628301],
        [0.37070787, 0.54500261, 0.57255832, 0.03774601]]])